/**
* World Storage API
* API ensuring interoperability between an authoring tool and a World Storage service
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* TrackablesApiImpl.h
*
* 
*/

#ifndef TRACKABLES_API_IMPL_H_
#define TRACKABLES_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>
#include <optional>

#include <api/TrackablesApi.h>


#include "model/Error.h"
#include "model/Trackable.h"
#include <string>

namespace org::openapitools::server::api
{

using namespace org::openapitools::server::model;

class TrackablesApiImpl : public org::openapitools::server::api::TrackablesApi {
public:
    explicit TrackablesApiImpl(const std::shared_ptr<Pistache::Rest::Router>& rtr);
    ~TrackablesApiImpl() override = default;

    void add_trackable(const std::optional<Trackable> &trackable, Pistache::Http::ResponseWriter &response);
    void get_trackables(Pistache::Http::ResponseWriter &response);

};

} // namespace org::openapitools::server::api



#endif
