#ifndef DEFAULTSOLARIMPL_H
#define DEFAULTSOLARIMPL_H

#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>
#include <optional>

#include <DefaultApi.h>

#include <Error.h>
#include <string>

namespace org::openapitools::server::implem
{

    using namespace org::openapitools::server::model;

    /**
     * @class
     * @brief implementation of  (class generated by OpenAPI-Generator), implements all the method defined with no tags in the API specification
     *
     */

    class DefaultSolARImpl : public org::openapitools::server::api::DefaultApi {

        public:
            explicit DefaultSolARImpl(const std::shared_ptr<Pistache::Rest::Router>& rtr);
            ~DefaultSolARImpl() override = default;


        // DefaultApi interface
        private:
            void get_version(Pistache::Http::ResponseWriter &response) override;
            void ping_get(Pistache::Http::ResponseWriter &response) override;
     };

}

#endif // DEFAULTSOLARIMPL_H
